### ISSUE TITLE
Omeka Classic 3.x

### ISSUE THREAD

**Issue by st1553** [Daniel-KM/Omeka-plugin-UpgradeToOmekaS#7]
Quick question. Does this work for Omeka 3.x? I need to upgrade classic 3.0.3 to S if possible. Thank you

**Comment by Daniel-KM** [comment]
This module and related ones will be upgraded in January.

**Comment by st1553** [comment]
Thank you Daniel. Happy holidays

**Comment by st1553** [comment]
@Daniel-KM , my guess is this isn't happening anymore?
